### ISSUE TITLE
Picture Preview not working for people invited with link

### ISSUE THREAD

**Issue by Thelch** [YunoHost-Apps/owncloud_ynh#23]
Hello,

i have created a link with the rights for Upload, download and show.

If you open the link you are not able to view a preview of the pictures in this space.

With my loged in Admin user its working.

If i open up the development console in Chrome i see this error:
`vendor-WsgKta2b.mjs:56 Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
Copyright 2023 Fonticons, Inc.

vendor-WsgKta2b.mjs:56 [UserManager] getUser: user not found in storage
index.html-Jkx6Jwj2.mjs:1  ownCloud Web UI 8.0.0-beta.2 
index.html-Jkx6Jwj2.mjs:1  Infinite Scale 5.0.0-beta.2 Community 
vendor-WsgKta2b.mjs:56 [UserManager] getUser: user not found in storage
vendor-WsgKta2b.mjs:56 [UserManager] getUser: user not found in storage
vendor-WsgKta2b.mjs:56 [UserManager] getUser: user not found in storage
vendor-WsgKta2b.mjs:56 [UserManager] getUser: user not found in storage`
![image](https://github.com/YunoHost-Apps/owncloud_ynh/assets/17222597/f751a26e-5157-4c29-86eb-5c41fa1a4763)

What could be the reason for this?

Versions: 
Yunohost 11.2.9.1 
ownCloud 5.0.0~ynh9

**Comment by Thelch** [comment]
i am not able to update to a newer version because the ownCLoud service is not starting:

```
Mai 31 09:43:33 ocis[3679689]: {"level":"warn","service":"nats","time":"2024-05-31T09:43:33+02:00","message":"Filestore [KV_service-registry] Stream state encountered internal inconsistency on recover"}
Mai 31 09:43:34 ocis[3679689]: The service account id has not been configured for ocm. Make sure your /var/www/owncloud config contains the proper values (e.g. by running ocis init or setting it manually in the config/corresponding environment variable).
Mai 31 09:43:34 systemd[1]: owncloud.service: Main process exited, code=exited, status=1/FAILURE
Mai 31 09:43:34 systemd[1]: owncloud.service: Failed with result 'exit-code'.
```

**Comment by ericgaspar** [comment]
Closing. The issue should be fixed. Please reopen an issue if needed
