### ISSUE TITLE
after installing, cannot login.

### ISSUE THREAD

**Issue by MothGirlMusic** [YunoHost-Apps/owncloud_ynh#7]
it appears that it accepts my login or something after inputting my information because it goes to "https://examplenextcloud.com/index.php/login?redirect_url=/index.php/apps/files/

but it keeps me still on the login screen. this is a fresh install of nextcloud. obviously not being able to log into it, i can't even modify it if i wanted.

**Comment by zamentur** [comment]
I think this issue should be posted on nextcloud package so i close it
